// Generated by Idea_Model/gen_scheduler_rtl_distilled_profiles_sv.py.
// Do not hand-edit; scheduler_rtl_distilled_profiles.py is normative.

import sched_pkg::*;
import sched_distilled_pkg::*;

module sched_distilled_profile_decode (
  input  logic [4:0]      profile_addr_i,
  output distilled_profile_t profile_o
);

  always_comb begin
    profile_o = '0;
    profile_o.profile_slot = 5'h1f;
    unique case (profile_addr_i)
      5'd0: begin
        profile_o.profile_slot = 5'd12;
        profile_o.logical_id = 3'd0;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_BOTH;
        profile_o.c2_dma_s3 = DMA_BOTH;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd1: begin
        profile_o.profile_slot = 5'd13;
        profile_o.logical_id = 3'd0;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_BOTH;
        profile_o.c3_dma_s3 = DMA_BOTH;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd2: begin
        profile_o.profile_slot = 5'd22;
        profile_o.logical_id = 3'd0;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd3: begin
        profile_o.profile_slot = 5'd25;
        profile_o.logical_id = 3'd0;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_BOTH;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd4: begin
        profile_o.profile_slot = 5'd14;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_SPLIT;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b1;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_IDMA;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd5: begin
        profile_o.profile_slot = 5'd6;
        profile_o.logical_id = 3'd0;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_PAIR;
        profile_o.selector_a = DIST_SEL_B0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_A;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_IDMA;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd6: begin
        profile_o.profile_slot = 5'd7;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_PAIR;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T1;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_IDMA;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd7: begin
        profile_o.profile_slot = 5'd8;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_PAIR;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T1;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_IDMA;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd8: begin
        profile_o.profile_slot = 5'd27;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_PAIR;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T1;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_BOTH;
        profile_o.c3_dma_s3 = DMA_BOTH;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd9: begin
        profile_o.profile_slot = 5'd9;
        profile_o.logical_id = 3'd2;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_PAIR;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T4;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_A;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_IDMA;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd10: begin
        profile_o.profile_slot = 5'd10;
        profile_o.logical_id = 3'd3;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_PAIR;
        profile_o.selector_a = DIST_SEL_T1;
        profile_o.selector_b = DIST_SEL_T2;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_IDMA;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_XDMA;
      end
      5'd11: begin
        profile_o.profile_slot = 5'd11;
        profile_o.logical_id = 3'd4;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_PAIR;
        profile_o.selector_a = DIST_SEL_T2;
        profile_o.selector_b = DIST_SEL_T3;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_IDMA;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_XDMA;
      end
      5'd12: begin
        profile_o.profile_slot = 5'd26;
        profile_o.logical_id = 3'd5;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_SPLIT;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_A;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_A;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_IDMA;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd13: begin
        profile_o.profile_slot = 5'd0;
        profile_o.logical_id = 3'd0;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_B0;
        profile_o.selector_b = DIST_SEL_B0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_BOTH;
        profile_o.c3_dma_s3 = DMA_BOTH;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd14: begin
        profile_o.profile_slot = 5'd1;
        profile_o.logical_id = 3'd0;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_B0;
        profile_o.selector_b = DIST_SEL_B0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_BOTH;
        profile_o.c2_dma_s3 = DMA_BOTH;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd15: begin
        profile_o.profile_slot = 5'd2;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_BOTH;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_BOTH;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd16: begin
        profile_o.profile_slot = 5'd3;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_BOTH;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_BOTH;
      end
      5'd17: begin
        profile_o.profile_slot = 5'd15;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_A;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_IDMA;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd18: begin
        profile_o.profile_slot = 5'd16;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_IDMA;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd19: begin
        profile_o.profile_slot = 5'd17;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd20: begin
        profile_o.profile_slot = 5'd18;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_BOTH;
        profile_o.c3_dma_s3 = DMA_BOTH;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd21: begin
        profile_o.profile_slot = 5'd19;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_BOTH;
        profile_o.c2_dma_s3 = DMA_BOTH;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd22: begin
        profile_o.profile_slot = 5'd20;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_IDMA;
        profile_o.c2_dma_s3 = DMA_BOTH;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd23: begin
        profile_o.profile_slot = 5'd21;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_A;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_XDMA;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd24: begin
        profile_o.profile_slot = 5'd23;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_XDMA;
        profile_o.c3_dma_s3 = DMA_BOTH;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd25: begin
        profile_o.profile_slot = 5'd24;
        profile_o.logical_id = 3'd1;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T0;
        profile_o.selector_b = DIST_SEL_T0;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_BOTH;
        profile_o.c2_dma_s3 = DMA_IDMA;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd26: begin
        profile_o.profile_slot = 5'd4;
        profile_o.logical_id = 3'd2;
        profile_o.logical_last = 1'b0;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T3;
        profile_o.selector_b = DIST_SEL_T3;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b1;
        profile_o.c3_active = 1'b0;
        profile_o.c2_shape_s1 = SHAPE_B;
        profile_o.c2_shape_s3 = SHAPE_B;
        profile_o.c3_shape_s1 = SHAPE_C;
        profile_o.c3_shape_s3 = SHAPE_C;
        profile_o.c2_dma_s1 = DMA_BOTH;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_BOTH;
        profile_o.c3_dma_s1 = DMA_NONE;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_NONE;
      end
      5'd27: begin
        profile_o.profile_slot = 5'd5;
        profile_o.logical_id = 3'd2;
        profile_o.logical_last = 1'b1;
        profile_o.family = DIST_FAMILY_SINGLE;
        profile_o.selector_a = DIST_SEL_T3;
        profile_o.selector_b = DIST_SEL_T3;
        profile_o.split_balanced = 1'b0;
        profile_o.c2_active = 1'b0;
        profile_o.c3_active = 1'b1;
        profile_o.c2_shape_s1 = SHAPE_C;
        profile_o.c2_shape_s3 = SHAPE_C;
        profile_o.c3_shape_s1 = SHAPE_B;
        profile_o.c3_shape_s3 = SHAPE_B;
        profile_o.c2_dma_s1 = DMA_NONE;
        profile_o.c2_dma_s3 = DMA_NONE;
        profile_o.c2_s2pf = DMA_NONE;
        profile_o.c3_dma_s1 = DMA_BOTH;
        profile_o.c3_dma_s3 = DMA_NONE;
        profile_o.c3_s2pf = DMA_BOTH;
      end
      default: profile_o.profile_slot = 5'h1f;
    endcase
  end

endmodule
